/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.screens;

import com.clases.Articulo;
import com.clases.Compra;
import com.clases.DetalleCompra;
import com.clases.Empleados;
import com.clases.Estado;
import com.clases.Proveedores;
import com.clases.SingletonUser;
import com.clases.TipoDePago;
import com.clases.Usuarios;
import com.dao.ArticuloJpaController;
import com.dao.CompraJpaController;
import com.dao.DetalleCompraJpaController;
import com.dao.EmpleadosJpaController;
import com.dao.EstadoJpaController;
import com.dao.ProveedoresJpaController;
import com.dao.TipoDePagoJpaController;
import static com.screens.FmrArticulos.ValidacionDeRepetidos;
import static com.screens.FmrVentas.t2;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Timestamp;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import static java.util.Collections.singleton;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.BadLocationException;

/**
 *
 * @author Ariel
 */
public class FmrCompras extends javax.swing.JFrame {    
    
    EntityManagerFactory emf = Persistence.createEntityManagerFactory("DB");
    
    CompraJpaController daoCompra = new CompraJpaController();
    ArticuloJpaController daoArticulo = new  ArticuloJpaController();    
    EmpleadosJpaController daoEmpleados = new EmpleadosJpaController();        
    TipoDePagoJpaController daoTipoPago = new TipoDePagoJpaController();
    ProveedoresJpaController daoProveedores = new ProveedoresJpaController();
    DetalleCompraJpaController daoDetalle = new DetalleCompraJpaController();
    
    Compra objCompra = new Compra();
    Articulo objArticulo = new  Articulo();
    Empleados objEmpleados = new Empleados();
    TipoDePago objTipoPago = new TipoDePago();        
    DetalleCompra objDetalle = new DetalleCompra();            
    
    static DefaultTableModel t3; 
    
    int idDetalle = 0;    
    private Usuarios usuarios = new Usuarios(); 
    DecimalFormat formato1 = new DecimalFormat("#.00");
    private SingletonUser singleton = SingletonUser.getUsuario(usuarios);    
   
    /**
     * Creates new form Compras
     */
    public FmrCompras() {
        initComponents();
      
        //ÍCONO
        this.setLocationRelativeTo(null);
        Image icon = new ImageIcon(getClass().getResource("/imagenes/IconoMicrocosmos.png")).getImage();
        setIconImage(icon); 
        
        //INICIALIZAR PANTALLA
        Inicializar();
        listaProveedores();                                                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        Txt_IdCompra = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Txt_IdEmpleado = new javax.swing.JTextField();
        Txt_Pedido = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        CBox_Proveedor = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Txt_Cantidad = new javax.swing.JTextField();
        Txt_PrecioC = new javax.swing.JTextField();
        Txt_Llegada = new javax.swing.JTextField();
        Btn_AñadirCant = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        Txt_PrecioU = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        Txt_SubC = new javax.swing.JTextField();
        Txt_FechaTomada = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_Compra = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        Btn_Agregar = new javax.swing.JButton();
        Btn_Cancelar = new javax.swing.JButton();
        Btn_Regresar = new javax.swing.JButton();
        Btn_Guardar = new javax.swing.JButton();
        Btn_Retirar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Compras - Microcosmos");
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        jPanel1.setBackground(new java.awt.Color(49, 49, 49));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoMicrocosmos.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel2.setBackground(new java.awt.Color(60, 63, 65));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("ID Compra");
        jLabel8.setMaximumSize(new java.awt.Dimension(120, 20));
        jLabel8.setMinimumSize(new java.awt.Dimension(120, 20));
        jLabel8.setPreferredSize(new java.awt.Dimension(120, 20));

        Txt_IdCompra.setEditable(false);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Empleado");
        jLabel9.setMaximumSize(new java.awt.Dimension(120, 20));
        jLabel9.setMinimumSize(new java.awt.Dimension(120, 20));
        jLabel9.setPreferredSize(new java.awt.Dimension(120, 20));

        Txt_IdEmpleado.setEditable(false);

        Txt_Pedido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Txt_PedidoKeyTyped(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Fecha de Pedido");
        jLabel12.setMaximumSize(new java.awt.Dimension(120, 20));
        jLabel12.setMinimumSize(new java.awt.Dimension(120, 20));
        jLabel12.setPreferredSize(new java.awt.Dimension(120, 20));

        CBox_Proveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        CBox_Proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBox_ProveedorActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Fecha de Llegada");
        jLabel20.setMaximumSize(new java.awt.Dimension(120, 20));
        jLabel20.setMinimumSize(new java.awt.Dimension(120, 20));
        jLabel20.setPreferredSize(new java.awt.Dimension(120, 20));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Cantidad:");
        jLabel10.setMaximumSize(new java.awt.Dimension(120, 20));
        jLabel10.setMinimumSize(new java.awt.Dimension(120, 20));
        jLabel10.setPreferredSize(new java.awt.Dimension(120, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Precio Compra:");
        jLabel11.setMaximumSize(new java.awt.Dimension(120, 20));
        jLabel11.setMinimumSize(new java.awt.Dimension(120, 20));
        jLabel11.setPreferredSize(new java.awt.Dimension(120, 20));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Total");
        jLabel16.setMaximumSize(new java.awt.Dimension(120, 20));
        jLabel16.setMinimumSize(new java.awt.Dimension(120, 20));
        jLabel16.setPreferredSize(new java.awt.Dimension(120, 20));

        Txt_Cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Txt_CantidadKeyTyped(evt);
            }
        });

        Txt_PrecioC.setEditable(false);

        Txt_Llegada.setEditable(false);

        Btn_AñadirCant.setBackground(new java.awt.Color(204, 204, 204));
        Btn_AñadirCant.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        Btn_AñadirCant.setText("Agregar");
        Btn_AñadirCant.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        Btn_AñadirCant.setFocusPainted(false);
        Btn_AñadirCant.setMaximumSize(new java.awt.Dimension(90, 20));
        Btn_AñadirCant.setMinimumSize(new java.awt.Dimension(90, 20));
        Btn_AñadirCant.setPreferredSize(new java.awt.Dimension(90, 20));
        Btn_AñadirCant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AñadirCantActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Proveedor");
        jLabel13.setMaximumSize(new java.awt.Dimension(120, 20));
        jLabel13.setMinimumSize(new java.awt.Dimension(120, 20));
        jLabel13.setPreferredSize(new java.awt.Dimension(120, 20));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Sub-Total");
        jLabel17.setMaximumSize(new java.awt.Dimension(120, 20));
        jLabel17.setMinimumSize(new java.awt.Dimension(120, 20));
        jLabel17.setPreferredSize(new java.awt.Dimension(120, 20));

        Txt_FechaTomada.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Txt_Pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_Llegada, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Txt_FechaTomada)
                            .addComponent(Txt_IdEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Txt_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Btn_AñadirCant, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Txt_PrecioU, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Txt_IdCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 34, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Txt_PrecioC, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CBox_Proveedor, 0, 95, Short.MAX_VALUE)
                            .addComponent(Txt_SubC))))
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(Txt_FechaTomada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CBox_Proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_SubC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_IdEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_Pedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_Llegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_IdCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_AñadirCant, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_PrecioU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_PrecioC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(38, 38, 38))
        );

        jPanel4.setBackground(new java.awt.Color(60, 63, 65));
        jPanel4.setMaximumSize(new java.awt.Dimension(62, 250));
        jPanel4.setMinimumSize(new java.awt.Dimension(62, 250));
        jPanel4.setPreferredSize(new java.awt.Dimension(62, 15));

        Tbl_Compra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id articulo", "Articulo", "Stock ", "Cantidad ", "Precio Compra", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tbl_Compra.setMaximumSize(new java.awt.Dimension(800, 230));
        Tbl_Compra.setMinimumSize(new java.awt.Dimension(800, 230));
        Tbl_Compra.setPreferredSize(new java.awt.Dimension(800, 230));
        Tbl_Compra.getTableHeader().setReorderingAllowed(false);
        Tbl_Compra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tbl_CompraMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Tbl_CompraMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(Tbl_Compra);
        if (Tbl_Compra.getColumnModel().getColumnCount() > 0) {
            Tbl_Compra.getColumnModel().getColumn(0).setResizable(false);
            Tbl_Compra.getColumnModel().getColumn(1).setResizable(false);
            Tbl_Compra.getColumnModel().getColumn(2).setResizable(false);
            Tbl_Compra.getColumnModel().getColumn(3).setResizable(false);
            Tbl_Compra.getColumnModel().getColumn(4).setResizable(false);
            Tbl_Compra.getColumnModel().getColumn(5).setResizable(false);
        }

        jPanel3.setBackground(new java.awt.Color(60, 63, 65));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Btn_Agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        Btn_Agregar.setText(" Buscar");
        Btn_Agregar.setToolTipText("Abre una nueva ventana donde se muestra una lista de todos los artículos.");
        Btn_Agregar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        Btn_Agregar.setFocusPainted(false);
        Btn_Agregar.setMaximumSize(new java.awt.Dimension(120, 50));
        Btn_Agregar.setMinimumSize(new java.awt.Dimension(120, 50));
        Btn_Agregar.setPreferredSize(new java.awt.Dimension(120, 50));
        Btn_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AgregarActionPerformed(evt);
            }
        });

        Btn_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        Btn_Cancelar.setText(" Cancelar");
        Btn_Cancelar.setToolTipText("Cancela el registro de la compra actual.");
        Btn_Cancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        Btn_Cancelar.setFocusPainted(false);
        Btn_Cancelar.setMaximumSize(new java.awt.Dimension(120, 50));
        Btn_Cancelar.setMinimumSize(new java.awt.Dimension(120, 50));
        Btn_Cancelar.setPreferredSize(new java.awt.Dimension(120, 50));
        Btn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CancelarActionPerformed(evt);
            }
        });

        Btn_Regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/regresar.png"))); // NOI18N
        Btn_Regresar.setText(" Regresar");
        Btn_Regresar.setToolTipText("Regresa a la pantalla de Menú Principal.");
        Btn_Regresar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        Btn_Regresar.setFocusPainted(false);
        Btn_Regresar.setMaximumSize(new java.awt.Dimension(120, 50));
        Btn_Regresar.setMinimumSize(new java.awt.Dimension(120, 50));
        Btn_Regresar.setPreferredSize(new java.awt.Dimension(120, 50));
        Btn_Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_RegresarActionPerformed(evt);
            }
        });

        Btn_Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anadir.png"))); // NOI18N
        Btn_Guardar.setText("Guardar");
        Btn_Guardar.setToolTipText("Guarda la compra ingresada actualmente.");
        Btn_Guardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        Btn_Guardar.setFocusPainted(false);
        Btn_Guardar.setMaximumSize(new java.awt.Dimension(120, 50));
        Btn_Guardar.setMinimumSize(new java.awt.Dimension(120, 50));
        Btn_Guardar.setPreferredSize(new java.awt.Dimension(120, 50));
        Btn_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_GuardarActionPerformed(evt);
            }
        });

        Btn_Retirar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/quitar.png"))); // NOI18N
        Btn_Retirar.setText(" Retirar");
        Btn_Retirar.setToolTipText("Retira el artículo seleccionado de la tabla de datos.");
        Btn_Retirar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        Btn_Retirar.setFocusPainted(false);
        Btn_Retirar.setMaximumSize(new java.awt.Dimension(120, 50));
        Btn_Retirar.setMinimumSize(new java.awt.Dimension(120, 50));
        Btn_Retirar.setPreferredSize(new java.awt.Dimension(120, 50));
        Btn_Retirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_RetirarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(Btn_Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(Btn_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(Btn_Retirar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(Btn_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(Btn_Regresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Retirar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_RegresarActionPerformed
        
        FmrMenú Menu = new FmrMenú();
        Menu.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_Btn_RegresarActionPerformed

    private void Btn_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_GuardarActionPerformed
        
        guardarCompra();        
        
    }//GEN-LAST:event_Btn_GuardarActionPerformed

    private void Tbl_CompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tbl_CompraMouseClicked
       
        int filas = Tbl_Compra.getRowCount();
        int filaSel = Tbl_Compra.getSelectedRow();
        
        if(filas == 0)
        {        
            JOptionPane.showMessageDialog(null, "No hay artículos para seleccionar.","¡Aviso!", JOptionPane.WARNING_MESSAGE);
        }else if(filas != 0 && filaSel == -1){
            JOptionPane.showMessageDialog(null, "Debe seleccionar un artículo.","¡Aviso!", JOptionPane.WARNING_MESSAGE);            
        }
        
    }//GEN-LAST:event_Tbl_CompraMouseClicked

    private void Btn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CancelarActionPerformed
       
       Inicializar();
       
    }//GEN-LAST:event_Btn_CancelarActionPerformed

    private void CBox_ProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBox_ProveedorActionPerformed

        

    }//GEN-LAST:event_CBox_ProveedorActionPerformed

    private void Btn_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AgregarActionPerformed
        
        FmrBuscarArticuloCompra buscarArtComp = new FmrBuscarArticuloCompra();
        buscarArtComp.setVisible(true);
        
    }//GEN-LAST:event_Btn_AgregarActionPerformed

    private void Tbl_CompraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tbl_CompraMouseEntered
      
        int filas = Tbl_Compra.getRowCount();
        
        if(filas != 0)
        {                        
            Btn_Retirar.setEnabled(true);                
            Btn_Cancelar.setEnabled(true);                                                            
            Btn_AñadirCant.setEnabled(true);
        }
        
    }//GEN-LAST:event_Tbl_CompraMouseEntered

    private void Txt_CantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_CantidadKeyTyped
        
        char n = evt.getKeyChar();

        // Permitir solo números
        if (!Character.isDigit(n))
        {
            evt.consume();
        }   
        
        //LIMITAR CANTIDAD DE CARÁCTERES A INGRESAR 
        if (Txt_Cantidad.getText().length() >= 4)
        {
            evt.consume();        
        }
        
    }//GEN-LAST:event_Txt_CantidadKeyTyped

    private void Txt_PedidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_PedidoKeyTyped
        
        char n = evt.getKeyChar();

        //Permitir solo números
        if (!Character.isDigit(n) && n != KeyEvent.VK_MINUS)
        {
            evt.consume();
        }      
        
        //LIMITAR CANTIDAD DE CARÁCTERES A INGRESAR 
        if (Txt_Pedido.getText().length() >= 10)
        {
            evt.consume();        
        }
        
    }//GEN-LAST:event_Txt_PedidoKeyTyped

    private void Btn_RetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_RetirarActionPerformed
        
        retirarArticulo();
        
    }//GEN-LAST:event_Btn_RetirarActionPerformed

    private void Btn_AñadirCantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AñadirCantActionPerformed
        
        int filas = Tbl_Compra.getRowCount();
        int filaSel = Tbl_Compra.getSelectedRow();
        
        if(filaSel == -1)
        {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un artículo para realizar esta acción.","¡Error!", JOptionPane.ERROR_MESSAGE);                        
        }else{
            añadirCantidad();   
            Txt_Cantidad.setText("1");
            Txt_PrecioU.setText("0.00");            
        }
        
    }//GEN-LAST:event_Btn_AñadirCantActionPerformed

    
    //MÉTODOS
    private void Inicializar()
    {
        //DESACTIVAR BOTONES         
        Btn_Retirar.setEnabled(false);                
        Btn_Guardar.setEnabled(false);
        Btn_Cancelar.setEnabled(false);                        
        Btn_AñadirCant.setEnabled(false);    
        Txt_FechaTomada.setVisible(false);        
        
        //OBTENER ID Y NOMBRE DE EMPLEADO Y MOSTRARLO
        Txt_IdEmpleado.setText(daoEmpleados.findEmpleados(singleton.getCuenta().getIdEmpleados()).getNombreEmpleado());                      
        
        //OBTENER, FORMATEAR Y MOSTRAR FECHA ACTUAL
        Date fecha = new Date(Calendar.getInstance().getTimeInMillis());
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        String fechaTexto = formatter.format(fecha);
        Txt_FechaTomada.setText(fechaTexto);
        
        Date fechaMostrar = new Date(Calendar.getInstance().getTimeInMillis());
        SimpleDateFormat formatterDate = new SimpleDateFormat("dd-MM-yyyy");
        String fechaMostrada = formatterDate.format(fechaMostrar);               
        
        Txt_Llegada.setText(fechaMostrada);         
        
        Txt_Cantidad.setText("1");
        Txt_SubC.setText("0.00");        
        Txt_PrecioC.setText("0.00");        
        Txt_Pedido.setText("");        
        
                
        facturaID();
        listaProveedores();                                                                
        
       //INICIALIZAR TABLA DE PRODUCTOS Y FACTURA        
       t3 = (DefaultTableModel)Tbl_Compra.getModel();
       t3.setRowCount(0);                 
       Tbl_Compra.setModel(t3);                   
    }
    
    private void guardarCompra()
    {       
        Icon icono = new ImageIcon(getClass().getResource("/imagenes/guardar.png"));
        
        if(validacionFecha(Txt_Pedido.getText()) == false)
        {
            JOptionPane.showMessageDialog(null, "Formato de fecha inválido.\nEl formato de la fecha es dd-MM-yyyy.","¡Error!", JOptionPane.ERROR_MESSAGE);            
        }else if(Txt_Pedido.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Tiene que ingresar la fecha en que realizó el pedido.\nEl formato de fecha es dd-MM-yyyy.","¡Error!", JOptionPane.ERROR_MESSAGE);            
        }else if(CBox_Proveedor.getSelectedItem().equals("Seleccione")){
            JOptionPane.showMessageDialog(null, "Tiene que seleccionar un proveedor.","¡Error!", JOptionPane.ERROR_MESSAGE);                        
        }else{
                                    
            String fechaP = Txt_Pedido.getText();
            String dia = "";
            String mes = "";
            String year = "";
          
            try{
                dia = Txt_Pedido.getText(0, 2);
                mes = Txt_Pedido.getText(3, 2);
                year = Txt_Pedido.getText(6, 4);
            } catch (BadLocationException ex) {
                Logger.getLogger(FmrCompras.class.getName()).log(Level.SEVERE, null, ex);
            }  
            
            String fechaPedido = year + "-" + mes + "-" + dia;                                                
            
            String fechaPBD = fechaPedido + " 00:00:00";
            String fechaL = Txt_FechaTomada.getText() + " 00:00:00";
                                    
            objCompra.setPrecioCompra(Double.parseDouble(Txt_SubC.getText()));
            objCompra.setTotalCompra(Double.parseDouble(Txt_PrecioC.getText()));
            objCompra.setFechaPedido(Timestamp.valueOf(fechaPBD));
            objCompra.setFechaRecibido(Timestamp.valueOf(fechaL));
            objCompra.setIdProveedor(GetIdProveedor(CBox_Proveedor.getSelectedItem().toString()));            
            objCompra.setIdEmpleados(daoEmpleados.findEmpleados(singleton.getCuenta().getIdEmpleados()).getIdEmpleados());
            objCompra.setIdEstado(1);
            
            try{
                daoCompra.edit(objCompra);
                JOptionPane.showMessageDialog(null, "Datos guardados correctamente.", "Compras", 0, icono);                                               
                
            }catch(Exception ex){
                Logger.getLogger(FmrCompras.class.getName()).log(Level.SEVERE, null, ex);                                
            }            
            
            //DETALLE DE COMPRA
            for(int i = 0; i < Tbl_Compra.getRowCount(); i++)
            {
                objDetalle.setCantidad(Integer.parseInt(String.valueOf(Tbl_Compra.getValueAt(i, 3))));
                objDetalle.setIdCompra(Integer.parseInt(Txt_IdCompra.getText()));            
                objDetalle.setIdArticulo(Integer.parseInt(String.valueOf(Tbl_Compra.getValueAt(i, 0))));

                try{
                    daoDetalle.edit(objDetalle);                      
                }catch(Exception ex){
                    Logger.getLogger(FmrCompras.class.getName()).log(Level.SEVERE, null, ex);                                                    
                }                
            }
            Inicializar();
        }
    }
    
    private void facturaID()
    {
        int orden = 1;
        daoCompra.findCompraEntities();
        
        int ordenFac = daoCompra.getCompraCount();
        
        if(orden < ordenFac)
        {
            orden = ordenFac + 1;            
        }
        
        String ordenCompra = String.valueOf(orden);
        
        Txt_IdCompra.setText(ordenCompra);        
    }
    
    public void listaProveedores()
    {
       CBox_Proveedor.removeAllItems();
        
        List<Proveedores> proveedores = this.daoProveedores.findProveedoresEntities();
  
        CBox_Proveedor.addItem("Seleccione");
      
        for(Proveedores Proveedores : proveedores )
        {
            String lista = Proveedores.getNombreProveedor();
           CBox_Proveedor.addItem(lista);                                
        };            
    }
    
    private static String GetNombreProveedor(int id)
    {
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("DB");
        EntityManager em = emf.createEntityManager();
        String select = "SELECT nombreProveedor FROM Proveedores WHERE idProveedor = '"+ id+ "'";
        Query query = em.createQuery(select);
    
        return query.getSingleResult().toString() ;            
    }   
        
    private static int GetIdProveedor(String Nombre)
    {
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("DB");
        EntityManager em = emf.createEntityManager();
        String select = "SELECT idProveedor FROM Proveedores WHERE nombreProveedor = '"+ Nombre+ "'";
        Query query = em.createQuery(select);
    
        return Integer.parseInt(query.getSingleResult().toString());           
    }             
    
    public static boolean validacionFecha(String text) 
    {
        if (text == null || !text.matches("^(0[1-9]|[12][0-9]|3[01])[- /.](0[1-9]|1[012])[- /.](19|20)\\d\\d$"))
        {
            return false;
        }        
        
        SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy");
        df.setLenient(false);
        
        try{
            df.parse(text);
            return true;
        }catch(ParseException ex){
            return false;
        }
    }
    
    private void añadirCantidad()
    {                
        if(Txt_PrecioU.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Debe ingresar la cantidad y el precio unitario.","¡Error!", JOptionPane.ERROR_MESSAGE);                                                            
        }else{                                    
    
            int filaSel = Tbl_Compra.getSelectedRow();        
            int cant = Integer.parseInt(Txt_Cantidad.getText());        
            double precio = Double.parseDouble(Txt_PrecioU.getText());
            double precioC = cant * precio;     
            double sub = 0;
            
            DecimalFormat formato2 = new DecimalFormat("#.00");
            
            if(precio == 0){
                JOptionPane.showMessageDialog(null, "Debe ingresar el precio unitario y debe ser mayor que 0.","¡Error!", JOptionPane.ERROR_MESSAGE);                                                                            
            }else if(cant > 0 && precio > 0){
                
                Tbl_Compra.setValueAt(cant, filaSel, 3);        
                Tbl_Compra.setValueAt(formato2.format(precio), filaSel, 4);
                Tbl_Compra.setValueAt(formato2.format(precioC), filaSel, 5);                
                                
                for(int i = 0; i < Tbl_Compra.getRowCount(); i++)
                {
                    sub = sub + Double.parseDouble(Tbl_Compra.getValueAt(i, 5).toString());
                }   
                
                Txt_SubC.setText(String.valueOf(formato2.format(sub)));                
                
                double subT = sub * 0.12;
                
                double total = subT + sub;
                
                Txt_PrecioC.setText(String.valueOf(formato2.format(total)));                
                
                if(Double.parseDouble(Txt_PrecioC.getText()) != 0)                    
                Btn_Guardar.setEnabled(true);
                
                Txt_Cantidad.setText("1");                                          
                Txt_PrecioU.setText("0");
            }else if(cant <= 0 && precio < 0){
                JOptionPane.showMessageDialog(null, "La cantidad debe ser mayor que 0.","¡Error!", JOptionPane.ERROR_MESSAGE);                                    
            }
        }
    }                                              
    
    private void retirarArticulo()
    {
        int fila = Tbl_Compra.getSelectedRow();        
        
        if(fila != -1)
        {
            t3.removeRow(fila);                                     
            
            int filas = t3.getRowCount();                        
            
            if(filas == 0)
            {
                Btn_Guardar.setEnabled(false);                
                Btn_Agregar.setEnabled(true);                
            }                        
        }else{
            JOptionPane.showMessageDialog(null, "Debe seleccionar un artículo para retirarlo.","Error!", JOptionPane.ERROR_MESSAGE);
        }                
    }  
    
    
                                   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FmrCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FmrCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FmrCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FmrCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FmrCompras().setVisible(true);
        });
    }                          
     
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Agregar;
    private javax.swing.JButton Btn_AñadirCant;
    private javax.swing.JButton Btn_Cancelar;
    private javax.swing.JButton Btn_Guardar;
    private javax.swing.JButton Btn_Regresar;
    private javax.swing.JButton Btn_Retirar;
    private javax.swing.JComboBox<String> CBox_Proveedor;
    private javax.swing.JTable Tbl_Compra;
    private javax.swing.JTextField Txt_Cantidad;
    private javax.swing.JTextField Txt_FechaTomada;
    private javax.swing.JTextField Txt_IdCompra;
    private javax.swing.JTextField Txt_IdEmpleado;
    private javax.swing.JTextField Txt_Llegada;
    private javax.swing.JTextField Txt_Pedido;
    private javax.swing.JTextField Txt_PrecioC;
    private javax.swing.JTextField Txt_PrecioU;
    private javax.swing.JTextField Txt_SubC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
