/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.screens;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author david
 * Para Sprint 1
 */
public class FmrConfiguraciones extends javax.swing.JFrame {

    /**
     * Creates new form Configuraciones
     */
    public FmrConfiguraciones() {
        initComponents();
        this.setLocationRelativeTo(null);
        Image icon = new ImageIcon(getClass().getResource("/imagenes/IconoMicrocosmos.png")).getImage();
        setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Btn_TipoDocumento = new javax.swing.JButton();
        Btn_TipoPago = new javax.swing.JButton();
        Btn_SeccionTienda = new javax.swing.JButton();
        Btn_Estado = new javax.swing.JButton();
        Btn_AreaLaboral = new javax.swing.JButton();
        Btn_PrecioHistorico = new javax.swing.JButton();
        Btn_Talla = new javax.swing.JButton();
        Btn_Menu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Btn_Facturas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Configuración - Microcosmos");
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        jPanel3.setBackground(new java.awt.Color(49, 49, 49));
        jPanel3.setMaximumSize(new java.awt.Dimension(770, 140));
        jPanel3.setMinimumSize(new java.awt.Dimension(770, 140));
        jPanel3.setPreferredSize(new java.awt.Dimension(770, 140));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoMicrocosmos.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(60, 63, 65));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setMaximumSize(new java.awt.Dimension(770, 32767));
        jPanel2.setMinimumSize(new java.awt.Dimension(770, 100));
        jPanel2.setPreferredSize(new java.awt.Dimension(770, 367));

        Btn_TipoDocumento.setBackground(new java.awt.Color(204, 204, 204));
        Btn_TipoDocumento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Btn_TipoDocumento.setText("Tipo de Documento");
        Btn_TipoDocumento.setToolTipText("Ingresa y modifica los tipos de documentos.");
        Btn_TipoDocumento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        Btn_TipoDocumento.setFocusPainted(false);
        Btn_TipoDocumento.setMaximumSize(new java.awt.Dimension(150, 50));
        Btn_TipoDocumento.setMinimumSize(new java.awt.Dimension(150, 50));
        Btn_TipoDocumento.setPreferredSize(new java.awt.Dimension(150, 50));
        Btn_TipoDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_TipoDocumentoActionPerformed(evt);
            }
        });

        Btn_TipoPago.setBackground(new java.awt.Color(204, 204, 204));
        Btn_TipoPago.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Btn_TipoPago.setText("Tipo de Pago");
        Btn_TipoPago.setToolTipText("Ingresa y modifica las formas de pago.");
        Btn_TipoPago.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        Btn_TipoPago.setFocusPainted(false);
        Btn_TipoPago.setMaximumSize(new java.awt.Dimension(150, 50));
        Btn_TipoPago.setMinimumSize(new java.awt.Dimension(150, 50));
        Btn_TipoPago.setName(""); // NOI18N
        Btn_TipoPago.setPreferredSize(new java.awt.Dimension(150, 50));
        Btn_TipoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_TipoPagoActionPerformed(evt);
            }
        });

        Btn_SeccionTienda.setBackground(new java.awt.Color(204, 204, 204));
        Btn_SeccionTienda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Btn_SeccionTienda.setText("Sección en Tienda");
        Btn_SeccionTienda.setToolTipText("Ingresa y modifica las secciones de la tienda.");
        Btn_SeccionTienda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        Btn_SeccionTienda.setFocusPainted(false);
        Btn_SeccionTienda.setMaximumSize(new java.awt.Dimension(150, 50));
        Btn_SeccionTienda.setMinimumSize(new java.awt.Dimension(150, 50));
        Btn_SeccionTienda.setPreferredSize(new java.awt.Dimension(150, 50));
        Btn_SeccionTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SeccionTiendaActionPerformed(evt);
            }
        });

        Btn_Estado.setBackground(new java.awt.Color(204, 204, 204));
        Btn_Estado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Btn_Estado.setText("Estados");
        Btn_Estado.setToolTipText("Ingresa y modifica los estados de las facturas.");
        Btn_Estado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        Btn_Estado.setFocusPainted(false);
        Btn_Estado.setMaximumSize(new java.awt.Dimension(150, 50));
        Btn_Estado.setMinimumSize(new java.awt.Dimension(150, 50));
        Btn_Estado.setPreferredSize(new java.awt.Dimension(150, 50));
        Btn_Estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_EstadoActionPerformed(evt);
            }
        });

        Btn_AreaLaboral.setBackground(new java.awt.Color(204, 204, 204));
        Btn_AreaLaboral.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Btn_AreaLaboral.setText("Área Laboral");
        Btn_AreaLaboral.setToolTipText("Ingresa y modifica las áreas laborales.");
        Btn_AreaLaboral.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        Btn_AreaLaboral.setFocusPainted(false);
        Btn_AreaLaboral.setMaximumSize(new java.awt.Dimension(150, 50));
        Btn_AreaLaboral.setMinimumSize(new java.awt.Dimension(150, 50));
        Btn_AreaLaboral.setPreferredSize(new java.awt.Dimension(150, 50));
        Btn_AreaLaboral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AreaLaboralActionPerformed(evt);
            }
        });

        Btn_PrecioHistorico.setBackground(new java.awt.Color(204, 204, 204));
        Btn_PrecioHistorico.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Btn_PrecioHistorico.setText("Precio Histórico");
        Btn_PrecioHistorico.setToolTipText("Ingresa y modifica los precios de los productos.");
        Btn_PrecioHistorico.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        Btn_PrecioHistorico.setFocusPainted(false);
        Btn_PrecioHistorico.setMaximumSize(new java.awt.Dimension(150, 50));
        Btn_PrecioHistorico.setMinimumSize(new java.awt.Dimension(150, 50));
        Btn_PrecioHistorico.setPreferredSize(new java.awt.Dimension(150, 50));
        Btn_PrecioHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_PrecioHistoricoActionPerformed(evt);
            }
        });

        Btn_Talla.setBackground(new java.awt.Color(204, 204, 204));
        Btn_Talla.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Btn_Talla.setText("Talla");
        Btn_Talla.setToolTipText("Ingresa y modifica las tallas de las prendas.");
        Btn_Talla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        Btn_Talla.setFocusPainted(false);
        Btn_Talla.setMaximumSize(new java.awt.Dimension(150, 50));
        Btn_Talla.setMinimumSize(new java.awt.Dimension(150, 50));
        Btn_Talla.setPreferredSize(new java.awt.Dimension(150, 50));
        Btn_Talla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_TallaActionPerformed(evt);
            }
        });

        Btn_Menu.setBackground(new java.awt.Color(204, 204, 204));
        Btn_Menu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Btn_Menu.setText("Regresar");
        Btn_Menu.setToolTipText("Regresa al menú principal.");
        Btn_Menu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        Btn_Menu.setFocusPainted(false);
        Btn_Menu.setMaximumSize(new java.awt.Dimension(150, 50));
        Btn_Menu.setMinimumSize(new java.awt.Dimension(150, 50));
        Btn_Menu.setPreferredSize(new java.awt.Dimension(150, 50));
        Btn_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_MenuActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CONFIGURACIÓN");

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Parámetros");
        jButton1.setToolTipText("Añade y verifica los datos del CAI.");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        jButton1.setFocusPainted(false);
        jButton1.setMaximumSize(new java.awt.Dimension(150, 50));
        jButton1.setMinimumSize(new java.awt.Dimension(150, 50));
        jButton1.setPreferredSize(new java.awt.Dimension(150, 50));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Btn_Facturas.setBackground(new java.awt.Color(204, 204, 204));
        Btn_Facturas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Btn_Facturas.setText("Historial de Facturas");
        Btn_Facturas.setToolTipText("Revisa e imprime las facturas registradas en el sistema.");
        Btn_Facturas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        Btn_Facturas.setFocusPainted(false);
        Btn_Facturas.setMaximumSize(new java.awt.Dimension(150, 50));
        Btn_Facturas.setMinimumSize(new java.awt.Dimension(150, 50));
        Btn_Facturas.setPreferredSize(new java.awt.Dimension(150, 50));
        Btn_Facturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_FacturasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Btn_AreaLaboral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btn_Estado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btn_TipoDocumento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btn_SeccionTienda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btn_Facturas, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Btn_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Btn_TipoPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Btn_PrecioHistorico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Btn_Talla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(190, 190, 190))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_TipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_TipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_SeccionTienda, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_PrecioHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_AreaLaboral, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Talla, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Btn_Estado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Btn_Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btn_Facturas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );

        Btn_TipoPago.getAccessibleContext().setAccessibleDescription("");
        jButton1.getAccessibleContext().setAccessibleDescription("Modifica parámetros de las facturas.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_TipoDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_TipoDocumentoActionPerformed
       
        FmrTipoDocumento TD = new FmrTipoDocumento();
        TD.setVisible(true);
        this.dispose();        
        
    }//GEN-LAST:event_Btn_TipoDocumentoActionPerformed

    private void Btn_TipoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_TipoPagoActionPerformed
       
        FmrTipoPago TP = new FmrTipoPago();
        TP.setVisible(true);
        this.dispose();   
        
    }//GEN-LAST:event_Btn_TipoPagoActionPerformed

    private void Btn_SeccionTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SeccionTiendaActionPerformed
        
        FmrSecciónTienda ST = new FmrSecciónTienda();
        ST.setVisible(true);
        this.dispose(); 
        
    }//GEN-LAST:event_Btn_SeccionTiendaActionPerformed

    private void Btn_PrecioHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_PrecioHistoricoActionPerformed
        
        FmrPrecioHistórico PH = new FmrPrecioHistórico();
        PH.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_Btn_PrecioHistoricoActionPerformed

    private void Btn_AreaLaboralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AreaLaboralActionPerformed
        
        FmrAreaLaboral PH = new FmrAreaLaboral();
        PH.setVisible(true);
        this.dispose();                 
            
    }//GEN-LAST:event_Btn_AreaLaboralActionPerformed

    private void Btn_TallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_TallaActionPerformed
       
        FmrTalla T = new FmrTalla();
        T.setVisible(true);
        this.dispose(); 
                
    }//GEN-LAST:event_Btn_TallaActionPerformed

    private void Btn_EstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_EstadoActionPerformed
        
        FmrEstado E = new FmrEstado();
        E.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_Btn_EstadoActionPerformed

    private void Btn_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_MenuActionPerformed
        
        FmrMenú M = new FmrMenú();
        M.setVisible(true);
        this.dispose(); 
        
    }//GEN-LAST:event_Btn_MenuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        FmrParametros P = new FmrParametros();
        P.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Btn_FacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_FacturasActionPerformed
        
        FmrHistorialFacturas Fact = new FmrHistorialFacturas();
        Fact.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_Btn_FacturasActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FmrConfiguraciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FmrConfiguraciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FmrConfiguraciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FmrConfiguraciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FmrConfiguraciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_AreaLaboral;
    private javax.swing.JButton Btn_Estado;
    private javax.swing.JButton Btn_Facturas;
    private javax.swing.JButton Btn_Menu;
    private javax.swing.JButton Btn_PrecioHistorico;
    private javax.swing.JButton Btn_SeccionTienda;
    private javax.swing.JButton Btn_Talla;
    private javax.swing.JButton Btn_TipoDocumento;
    private javax.swing.JButton Btn_TipoPago;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
