/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.screens;

import static com.screens.FmrPagoMixto.canEfectivo;
import static com.screens.FmrPagoMixto.canTarjeta;
import static com.screens.FmrPagoMixto.numTarjeta;
import java.awt.Image;
import java.text.DecimalFormat;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Ariel
 */
public class FmrTarjeta extends javax.swing.JFrame {

    public static String nTarjeta;
    public static int cancel = 0;
    
    DecimalFormat formato1 = new DecimalFormat("#.00");        
    
    /**
     * Creates new form FmrTarjeta
     */
    public FmrTarjeta() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        //ÍCONO
        Image icon = new ImageIcon(getClass().getResource("/imagenes/barra-de-busqueda.png")).getImage();
        setIconImage(icon); 
        
        Inicializar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Txt_Tarjeta = new javax.swing.JTextField();
        Txt_MontoTotal = new javax.swing.JTextField();
        Btn_AceptarT = new javax.swing.JButton();
        Btn_CancelarT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tarjeta Crédito - Microcosmos");
        setMaximumSize(new java.awt.Dimension(300, 150));
        setMinimumSize(new java.awt.Dimension(300, 150));
        setResizable(false);
        setSize(new java.awt.Dimension(300, 150));

        jPanel3.setBackground(new java.awt.Color(60, 63, 65));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Número Tarjeta");
        jLabel10.setMaximumSize(new java.awt.Dimension(120, 20));
        jLabel10.setMinimumSize(new java.awt.Dimension(120, 20));
        jLabel10.setPreferredSize(new java.awt.Dimension(120, 20));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Total");
        jLabel14.setMaximumSize(new java.awt.Dimension(120, 20));
        jLabel14.setMinimumSize(new java.awt.Dimension(120, 20));
        jLabel14.setPreferredSize(new java.awt.Dimension(120, 20));

        Txt_Tarjeta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Txt_TarjetaKeyTyped(evt);
            }
        });

        Txt_MontoTotal.setEditable(false);

        Btn_AceptarT.setText("Aceptar");
        Btn_AceptarT.setToolTipText("Guarda los datos de la tarjeta y los montos pagados.");
        Btn_AceptarT.setFocusPainted(false);
        Btn_AceptarT.setMaximumSize(new java.awt.Dimension(90, 22));
        Btn_AceptarT.setMinimumSize(new java.awt.Dimension(90, 22));
        Btn_AceptarT.setPreferredSize(new java.awt.Dimension(90, 22));
        Btn_AceptarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AceptarTActionPerformed(evt);
            }
        });

        Btn_CancelarT.setText("Cancelar");
        Btn_CancelarT.setToolTipText("Cancela la acción actual y regresa a la pantalla de Venta.");
        Btn_CancelarT.setFocusPainted(false);
        Btn_CancelarT.setMaximumSize(new java.awt.Dimension(90, 22));
        Btn_CancelarT.setMinimumSize(new java.awt.Dimension(90, 22));
        Btn_CancelarT.setPreferredSize(new java.awt.Dimension(90, 22));
        Btn_CancelarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CancelarTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Txt_Tarjeta))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Btn_AceptarT, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Txt_MontoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_CancelarT, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 52, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_Tarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_MontoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_AceptarT, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_CancelarT, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Txt_TarjetaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_TarjetaKeyTyped

        char n = evt.getKeyChar();

        // Permitir solo números
        if (!Character.isDigit(n))
        {
            evt.consume();
        }

        // Maximo de carácteres permitidos
        if (Txt_Tarjeta.getText().length() >= 22)
        {
            evt.consume();            
        }

    }//GEN-LAST:event_Txt_TarjetaKeyTyped

    private void Btn_AceptarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AceptarTActionPerformed

        //cancel = 1;
        aceptarPago();
        

    }//GEN-LAST:event_Btn_AceptarTActionPerformed

    private void Btn_CancelarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CancelarTActionPerformed

        cancel = 2;
        this.dispose();

    }//GEN-LAST:event_Btn_CancelarTActionPerformed

    //METODOS
    private void Inicializar()
    {        
        double ventaTotal = FmrVentas.totalV;
        
        String textVenta = String.valueOf(formato1.format(ventaTotal));
        
        Txt_MontoTotal.setText(textVenta);            
        
    } 
    
    
    private void aceptarPago()
    {           
        Pattern pass = Pattern.compile("^(?:4[0-9]{12}(?:[0-9]{3})?|(?:5[1-5][0-9]{2}|222[1-9]|22[3-9][0-9]|2[3-6][0-9]{2}|27[01][0-9]|2720)[0-9]{12}|3[47][0-9]{13}|3(?:0[0-5]|[68][0-9])[0-9]{11}|6(?:011|5[0-9]{2})[0-9]{12}|(?:2131|1800|35\\d{3})\\d{11})$");          
        Matcher mat = pass.matcher(Txt_Tarjeta.getText());
        
        if(mat.matches())
        {
            if(Txt_Tarjeta.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null, "Debe ingresar un número de tarjeta de crédito.", "¡Error!", JOptionPane.ERROR_MESSAGE);
            }else if (Txt_Tarjeta.getText().length() < 16){
                JOptionPane.showMessageDialog(null, "La tarjeta debe contener 16 dígitos.", "¡Error!", JOptionPane.ERROR_MESSAGE);
            }else{                                           
                String tarjeta = Txt_Tarjeta.getText();            
            
                //ALMACENANDO DATOS OBTENIDOS EN VARIABLES GLOBALES
                nTarjeta = tarjeta;             
                                    
                JOptionPane.showMessageDialog(null, "Datos guardados correctamente.");                                        
                this.dispose();
            }
        }
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FmrTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FmrTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FmrTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FmrTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FmrTarjeta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_AceptarT;
    private javax.swing.JButton Btn_CancelarT;
    private javax.swing.JTextField Txt_MontoTotal;
    private javax.swing.JTextField Txt_Tarjeta;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
