/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.screens;

import com.clases.Usuarios;
import com.dao.UsuariosJpaController;
import java.awt.Image;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ariel
 */
public class FmrUsuarios extends javax.swing.JFrame {
    
    EntityManagerFactory emf = Persistence.createEntityManagerFactory("DB");
    UsuariosJpaController daoUsuarios = new UsuariosJpaController();
    Usuarios objUsuario = new Usuarios();

    /**
     * Creates new form FmrUsuarios
     */
    public FmrUsuarios() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        //ÍCONO
        Image icon = new ImageIcon(getClass().getResource("/imagenes/IconoMicrocosmos.png")).getImage();
        setIconImage(icon);
        
        //INICIALIZAR PANTALLA
        actualizarUsuario();        
        Btn_CambiarPass.setEnabled(false);
        Btn_Activar.setEnabled(false);  
        Btn_Limpiar.setEnabled(false);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Txt_IdUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Txt_IdEmpleado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Txt_UserName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Txt_Contraseña = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Txt_Intentos = new javax.swing.JTextField();
        Txt_Estado = new javax.swing.JTextField();
        Txt_Admin = new javax.swing.JTextField();
        Btn_Admin = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        Txt_Confirmar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Usuarios = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        Btn_CambiarPass = new javax.swing.JButton();
        Btn_Activar = new javax.swing.JButton();
        Btn_Return = new javax.swing.JButton();
        Btn_Limpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Usuarios - Microcosmos");
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(49, 49, 49));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoMicrocosmos.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(60, 63, 65));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setMaximumSize(new java.awt.Dimension(800, 230));
        jPanel2.setMinimumSize(new java.awt.Dimension(800, 230));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 230));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("ID Usuario");
        jLabel2.setMaximumSize(new java.awt.Dimension(120, 20));
        jLabel2.setMinimumSize(new java.awt.Dimension(120, 20));
        jLabel2.setPreferredSize(new java.awt.Dimension(120, 20));

        Txt_IdUsuario.setEditable(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("ID Empleado");
        jLabel3.setMaximumSize(new java.awt.Dimension(120, 20));
        jLabel3.setMinimumSize(new java.awt.Dimension(120, 20));
        jLabel3.setPreferredSize(new java.awt.Dimension(120, 20));

        Txt_IdEmpleado.setEditable(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Nombre Usuario");
        jLabel4.setMaximumSize(new java.awt.Dimension(120, 20));
        jLabel4.setMinimumSize(new java.awt.Dimension(120, 20));
        jLabel4.setPreferredSize(new java.awt.Dimension(120, 20));

        Txt_UserName.setEditable(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Contraseña");
        jLabel5.setMaximumSize(new java.awt.Dimension(120, 20));
        jLabel5.setMinimumSize(new java.awt.Dimension(120, 20));
        jLabel5.setPreferredSize(new java.awt.Dimension(120, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Estado");
        jLabel6.setMaximumSize(new java.awt.Dimension(120, 20));
        jLabel6.setMinimumSize(new java.awt.Dimension(120, 20));
        jLabel6.setPreferredSize(new java.awt.Dimension(120, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Administrador");
        jLabel7.setMaximumSize(new java.awt.Dimension(120, 20));
        jLabel7.setMinimumSize(new java.awt.Dimension(120, 20));
        jLabel7.setPreferredSize(new java.awt.Dimension(120, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Número de Intentos");
        jLabel8.setMaximumSize(new java.awt.Dimension(120, 20));
        jLabel8.setMinimumSize(new java.awt.Dimension(120, 20));
        jLabel8.setPreferredSize(new java.awt.Dimension(120, 20));

        Txt_Intentos.setEditable(false);

        Txt_Estado.setEditable(false);
        Txt_Estado.setMaximumSize(new java.awt.Dimension(75, 20));
        Txt_Estado.setMinimumSize(new java.awt.Dimension(75, 20));
        Txt_Estado.setPreferredSize(new java.awt.Dimension(75, 20));

        Txt_Admin.setEditable(false);

        Btn_Admin.setText("Administrador");
        Btn_Admin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        Btn_Admin.setFocusPainted(false);
        Btn_Admin.setMaximumSize(new java.awt.Dimension(85, 30));
        Btn_Admin.setMinimumSize(new java.awt.Dimension(85, 30));
        Btn_Admin.setPreferredSize(new java.awt.Dimension(85, 30));
        Btn_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AdminActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Confirmar Contraseña");
        jLabel9.setMaximumSize(new java.awt.Dimension(120, 20));
        jLabel9.setMinimumSize(new java.awt.Dimension(120, 20));
        jLabel9.setPreferredSize(new java.awt.Dimension(120, 20));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Txt_IdEmpleado)
                                .addGap(85, 85, 85))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Txt_Contraseña))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Txt_UserName, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Txt_IdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Txt_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Txt_Intentos, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                            .addComponent(Txt_Admin))
                        .addGap(18, 18, 18)
                        .addComponent(Btn_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(123, 123, 123))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Txt_Confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_IdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_Intentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_IdEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_UserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Txt_Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_Confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        Txt_Estado.getAccessibleContext().setAccessibleDescription("");
        Btn_Admin.getAccessibleContext().setAccessibleDescription("Otorga privilegios de administrador al usuario seleccionado.");

        jTable_Usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Usuario", "Nombre", "Contraseña", "Número de Intentos", "Estado", "Admin", "ID Empleado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_Usuarios.getTableHeader().setReorderingAllowed(false);
        jTable_Usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_UsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Usuarios);
        if (jTable_Usuarios.getColumnModel().getColumnCount() > 0) {
            jTable_Usuarios.getColumnModel().getColumn(0).setResizable(false);
            jTable_Usuarios.getColumnModel().getColumn(1).setResizable(false);
            jTable_Usuarios.getColumnModel().getColumn(2).setResizable(false);
            jTable_Usuarios.getColumnModel().getColumn(3).setResizable(false);
            jTable_Usuarios.getColumnModel().getColumn(4).setResizable(false);
            jTable_Usuarios.getColumnModel().getColumn(5).setResizable(false);
            jTable_Usuarios.getColumnModel().getColumn(6).setResizable(false);
        }

        jPanel4.setBackground(new java.awt.Color(60, 63, 65));
        jPanel4.setMaximumSize(new java.awt.Dimension(800, 130));
        jPanel4.setMinimumSize(new java.awt.Dimension(800, 130));
        jPanel4.setPreferredSize(new java.awt.Dimension(800, 130));

        Btn_CambiarPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/contrasena.png"))); // NOI18N
        Btn_CambiarPass.setText("Cambiar Contraseña");
        Btn_CambiarPass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        Btn_CambiarPass.setFocusPainted(false);
        Btn_CambiarPass.setMaximumSize(new java.awt.Dimension(160, 50));
        Btn_CambiarPass.setMinimumSize(new java.awt.Dimension(160, 50));
        Btn_CambiarPass.setPreferredSize(new java.awt.Dimension(160, 50));
        Btn_CambiarPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CambiarPassActionPerformed(evt);
            }
        });

        Btn_Activar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/estado.png"))); // NOI18N
        Btn_Activar.setText("Activar Usuario");
        Btn_Activar.setActionCommand(" Activar Usuario");
        Btn_Activar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        Btn_Activar.setFocusPainted(false);
        Btn_Activar.setMaximumSize(new java.awt.Dimension(160, 50));
        Btn_Activar.setMinimumSize(new java.awt.Dimension(160, 50));
        Btn_Activar.setPreferredSize(new java.awt.Dimension(160, 50));
        Btn_Activar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ActivarActionPerformed(evt);
            }
        });

        Btn_Return.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/regresar.png"))); // NOI18N
        Btn_Return.setText(" Regresar");
        Btn_Return.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        Btn_Return.setFocusPainted(false);
        Btn_Return.setMaximumSize(new java.awt.Dimension(160, 50));
        Btn_Return.setMinimumSize(new java.awt.Dimension(160, 50));
        Btn_Return.setPreferredSize(new java.awt.Dimension(160, 50));
        Btn_Return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ReturnActionPerformed(evt);
            }
        });

        Btn_Limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limpiar.png"))); // NOI18N
        Btn_Limpiar.setText(" Limpiar");
        Btn_Limpiar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        Btn_Limpiar.setFocusPainted(false);
        Btn_Limpiar.setMaximumSize(new java.awt.Dimension(160, 50));
        Btn_Limpiar.setMinimumSize(new java.awt.Dimension(160, 50));
        Btn_Limpiar.setPreferredSize(new java.awt.Dimension(160, 50));
        Btn_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_LimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(Btn_CambiarPass, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(Btn_Activar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(Btn_Limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(Btn_Return, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_CambiarPass, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Activar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Return, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        Btn_CambiarPass.getAccessibleContext().setAccessibleDescription("Cambia la contraseña del usuario seleccionado.");
        Btn_Activar.getAccessibleContext().setAccessibleDescription("Permite activar o desactivar el elemento seleccionado.");
        Btn_Return.getAccessibleContext().setAccessibleDescription("Vuelve a la pantalla anterior.");
        Btn_Limpiar.getAccessibleContext().setAccessibleDescription("Borra los datos de todos los campos de texto.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //BOTONES Y TABLA   
    private void Btn_CambiarPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CambiarPassActionPerformed
        
        cambiarPass();        
        
    }//GEN-LAST:event_Btn_CambiarPassActionPerformed

    private void Btn_ActivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ActivarActionPerformed
               
        int fila = jTable_Usuarios.getSelectedRow();
        
        if(fila != -1)
        {
            estadoUsuario();            
        }else{
            JOptionPane.showMessageDialog(this, "Debe seleccionar el elemento a Activar o Desactivar en la Tabla");
        }             
                       
    }//GEN-LAST:event_Btn_ActivarActionPerformed
      
    private void Btn_ReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ReturnActionPerformed
        
        FmrMenú M = new FmrMenú();
        M.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_Btn_ReturnActionPerformed

    private void jTable_UsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_UsuariosMouseClicked
        
        int fila = jTable_Usuarios.getSelectedRow();
        
        if(fila == -1)
        {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una Fila");                    
        }else{
            Btn_CambiarPass.setEnabled(true);
            Btn_Activar.setEnabled(true);  
            Btn_Limpiar.setEnabled(true);
            
            String IdU = jTable_Usuarios.getValueAt(fila, 0).toString();
            String Nombre = jTable_Usuarios.getValueAt(fila, 1).toString();
            String Contraseña = jTable_Usuarios.getValueAt(fila, 2).toString();
            String Intentos = jTable_Usuarios.getValueAt(fila, 3).toString();
            String Estado = jTable_Usuarios.getValueAt(fila, 4).toString();
            String Admin = jTable_Usuarios.getValueAt(fila, 5).toString();
            String IdE = jTable_Usuarios.getValueAt(fila, 6).toString();
            
            Txt_IdUsuario.setText(IdU);
            Txt_UserName.setText(Nombre);
            Txt_Contraseña.setText(Contraseña);
            Txt_Intentos.setText(Intentos);
            Txt_Estado.setText(Estado); 
            Txt_Admin.setText(Admin);
            Txt_IdEmpleado.setText(IdE);                       
            
            if(Estado == "true")
            {
                Btn_Activar.setText("Desactivar Usuario");
                Btn_Admin.setEnabled(true);
            }else{ 
                Btn_Activar.setText("Activar Usuario");   
                Btn_Admin.setEnabled(false);
                Btn_CambiarPass.setEnabled(false);
            }     
            
            if(Estado == "true")
            {
                Txt_Estado.setText("Activo");                                                 
            }else if(Estado == "false"){
                Txt_Estado.setText("Desactivado"); 
            }
            
            if(Admin == "true")
            {
                Txt_Admin.setText("Si");                
            }else{
                Txt_Admin.setText("No");
            }
        }        
    }//GEN-LAST:event_jTable_UsuariosMouseClicked

    private void Btn_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_LimpiarActionPerformed
        
        limpiarUsuario();        
        Btn_Limpiar.setEnabled(false);
        Btn_Admin.setEnabled(false);
        
    }//GEN-LAST:event_Btn_LimpiarActionPerformed

    private void Btn_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AdminActionPerformed
        
        int fila = jTable_Usuarios.getSelectedRow();
        
        if(fila != -1)
        {                      
            adminUsuario();                                                                              
        }else{
            JOptionPane.showMessageDialog(null, "Debe seleccionar un usuario para realizar esta acción.","Error!", JOptionPane.ERROR_MESSAGE);
        }                     
        
    }//GEN-LAST:event_Btn_AdminActionPerformed
    
            
    //FUNCIONES
    private void cambiarPass()
    {
        String contra = Txt_Contraseña.getText();
        String pass2 = Txt_Confirmar.getText();
        
         Pattern pass = Pattern.compile("^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=])(?=\\S+$).{8,}$");        
         Matcher mat = pass.matcher(Txt_Contraseña.getText());
         
         if(mat.matches())
         {
             if(contra.equals(pass2))            
             {                 
                 JOptionPane.showMessageDialog(this, "Las contraseñas coinciden.");                        
                 
                 objUsuario.setIdUsuario(Integer.parseInt(Txt_IdUsuario.getText()));
                 objUsuario.setIdEmpleados(Integer.parseInt(Txt_IdEmpleado.getText()));
                 objUsuario.setNombreUsuario(Txt_UserName.getText());
                 objUsuario.setContraseña(Txt_Contraseña.getText());
                 objUsuario.setNumeroDeIntentos(Integer.parseInt(Txt_Intentos.getText()));
                 objUsuario.setAdmin(Boolean.parseBoolean(Txt_Admin.getText()));
                 //objUsuario.setActivoUsuario(Boolean.parseBoolean(Txt_Estado.getText()));
                 
                 try{
                     daoUsuarios.edit(objUsuario);
                     actualizarUsuario();
                     JOptionPane.showMessageDialog(this, "La contraseña se actualizó correctamente.");
                 }catch(Exception ex){
                     Logger.getLogger(FmrUsuarios.class.getName()).log(Level.SEVERE, null, ex);
                 }                 
             }else{
                 JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden.","Contraseña incorrecta", JOptionPane.ERROR_MESSAGE);
             }             
         }else{
             JOptionPane.showMessageDialog(null, "La contraseña debe contener al menos un número, una letra mayúscula y minúscula, un carácter especial y mínimo 8 dígitos.","Formato de contraseña incorrecto", JOptionPane.ERROR_MESSAGE);             
         }                  
    }
    
    private void actualizarUsuario()
    {
        DefaultTableModel t = (DefaultTableModel)jTable_Usuarios.getModel();
        t.setRowCount(0);
        jTable_Usuarios.setModel(t);                
        
        List<Usuarios> usuario = this.daoUsuarios.findUsuariosEntities();
        
        String s;
        for(Usuarios Usuarios : usuario)
        {
            if(Usuarios.isActivoUsuario() == true) 
            {
                s = "Activado";                
            }else{
                s = "Desactivado";
            }
            
            t.addRow(
                    new Object[]{
                        Usuarios.getIdUsuario(),
                        Usuarios.getNombreUsuario(),
                        Usuarios.getContraseña(),
                        Usuarios.getNumeroDeIntentos(),
                        Usuarios.isActivoUsuario(),
                        Usuarios.isAdmin(),
                        Usuarios.getIdEmpleados(),
                        s
                    });
        }       
    }
    
    private void estadoUsuario()
    {
        int fila = jTable_Usuarios.getSelectedRow();        
        
        String estado = Txt_Estado.getText();
        
        if(estado.equals("Activo"))
        {            
            objUsuario.setIdUsuario(Integer.parseInt(Txt_IdUsuario.getText()));
            objUsuario.setNombreUsuario(jTable_Usuarios.getValueAt(fila, 1).toString());            
            objUsuario.setContraseña(jTable_Usuarios.getValueAt(fila, 2).toString());
            objUsuario.setNumeroDeIntentos(Integer.parseInt(Txt_Intentos.getText()));            
            objUsuario.setAdmin(Boolean.parseBoolean(Txt_Admin.getText()));
            objUsuario.setIdEmpleados(Integer.parseInt(Txt_IdEmpleado.getText()));
            objUsuario.setActivoUsuario(false);            
                        
            try{
                daoUsuarios.edit(objUsuario);
                actualizarUsuario();
                Btn_Activar.setText("Activar Usuario");
                JOptionPane.showMessageDialog(this, "Se desactivó correctamente");            
            }catch(Exception ex){
                Logger.getLogger(FmrUsuarios.class.getName()).log(Level.SEVERE, null, ex);            
            }
        
            limpiarUsuario();
            Btn_CambiarPass.setEnabled(true);
            Btn_Limpiar.setEnabled(false);
            
        }else{            
            objUsuario.setIdUsuario(Integer.parseInt(Txt_IdUsuario.getText()));
            objUsuario.setNombreUsuario(jTable_Usuarios.getValueAt(fila, 1).toString());            
            objUsuario.setContraseña(jTable_Usuarios.getValueAt(fila, 2).toString());
            objUsuario.setNumeroDeIntentos(Integer.parseInt(Txt_Intentos.getText()));            
            objUsuario.setAdmin(Boolean.parseBoolean(Txt_Admin.getText()));
            objUsuario.setIdEmpleados(Integer.parseInt(Txt_IdEmpleado.getText()));
            objUsuario.setActivoUsuario(true);  
            
            try{
                daoUsuarios.edit(objUsuario);
                actualizarUsuario();
                Btn_Activar.setText("Desactivar Usuario");
                JOptionPane.showMessageDialog(this, "Se activó correctamente");            
            }catch(Exception ex){
                Logger.getLogger(FmrUsuarios.class.getName()).log(Level.SEVERE, null, ex);            
            }
            
            limpiarUsuario();
            Btn_CambiarPass.setEnabled(true);
            Btn_Limpiar.setEnabled(false);            
        }         
        
    }
    
    private void adminUsuario()
    {
        int fila = jTable_Usuarios.getSelectedRow();
        
        String admin = Txt_Admin.getText();
        
        if(admin.equals("Si"))
        {
            objUsuario.setIdUsuario(Integer.parseInt(Txt_IdUsuario.getText()));
            objUsuario.setNombreUsuario(jTable_Usuarios.getValueAt(fila, 1).toString());            
            objUsuario.setContraseña(jTable_Usuarios.getValueAt(fila, 2).toString());
            objUsuario.setNumeroDeIntentos(Integer.parseInt(Txt_Intentos.getText()));                        
            objUsuario.setIdEmpleados(Integer.parseInt(Txt_IdEmpleado.getText()));                        
            objUsuario.setAdmin(false);
            
            try{
                daoUsuarios.edit(objUsuario);
                actualizarUsuario();
                JOptionPane.showMessageDialog(this, "El usuario ya no es Administrador.");
            }catch(Exception ex){
                Logger.getLogger(FmrUsuarios.class.getName()).log(Level.SEVERE, null, ex);                                            
            }                                  
        }else{
            objUsuario.setIdUsuario(Integer.parseInt(Txt_IdUsuario.getText()));
            objUsuario.setNombreUsuario(jTable_Usuarios.getValueAt(fila, 1).toString());            
            objUsuario.setContraseña(jTable_Usuarios.getValueAt(fila, 2).toString());
            objUsuario.setNumeroDeIntentos(Integer.parseInt(Txt_Intentos.getText()));                        
            objUsuario.setIdEmpleados(Integer.parseInt(Txt_IdEmpleado.getText()));            
            objUsuario.setAdmin(true);
            
            try{
                daoUsuarios.edit(objUsuario);
                actualizarUsuario();
                JOptionPane.showMessageDialog(this, "El usuario ahora es Administrador.");
            }catch(Exception ex){
                Logger.getLogger(FmrUsuarios.class.getName()).log(Level.SEVERE, null, ex);                                            
            }                                                           
        }        
    }
    
    private void limpiarUsuario()
    {
        Btn_CambiarPass.setEnabled(true);
        Btn_Activar.setEnabled(false);
        
        Txt_IdUsuario.setText("");
        Txt_IdEmpleado.setText("");
        Txt_UserName.setText("");
        Txt_Contraseña.setText("");
        Txt_Confirmar.setText("");
        Txt_Intentos.setText("");
        Txt_Estado.setText("");
        Txt_Admin.setText("");             
    }        
    
    public static boolean contraseñaRepetida(String Contraseña)
    {             
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("DB");
        EntityManager em = emf.createEntityManager();
                    
        String select = "SELECT idUsuario FROM Usuarios WHERE contraseña  = '"+Contraseña+ "'";
   
        Query query = em.createQuery(select);
       
        if(query.getResultList().size() == 0)
        {
            return false;
             
        }else{
            return true;                
        }             
    }
            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FmrUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FmrUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FmrUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FmrUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FmrUsuarios().setVisible(true);
            }
        });
    }        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Activar;
    private javax.swing.JButton Btn_Admin;
    private javax.swing.JButton Btn_CambiarPass;
    private javax.swing.JButton Btn_Limpiar;
    private javax.swing.JButton Btn_Return;
    private javax.swing.JTextField Txt_Admin;
    private javax.swing.JTextField Txt_Confirmar;
    private javax.swing.JTextField Txt_Contraseña;
    private javax.swing.JTextField Txt_Estado;
    private javax.swing.JTextField Txt_IdEmpleado;
    private javax.swing.JTextField Txt_IdUsuario;
    private javax.swing.JTextField Txt_Intentos;
    private javax.swing.JTextField Txt_UserName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Usuarios;
    // End of variables declaration//GEN-END:variables
}
